development:
  adapter: mysql2
  hostname: localhost
  database: furista_development
  username: root
  password: "123"

test:
  adapter: mysql2
  hostname: localhost
  database: furista_test
  username: root
  password: "123"

cucumber:
  adapter: mysql2
  hostname: localhost
  database: furista_production
  username: root
  password: "123"