development:
  adapter: mysql2
  hostname: localhost
  database: furista_development
  username: root
  password: "mahheki"

test:
  adapter: mysql2
  hostname: localhost
  database: furista_test
  username: root
  password: "mahheki"

cucumber:
  adapter: mysql2
  hostname: localhost
  database: furista_test
  username: root
  password: "mahheki"